version: '3'
services:
  db_local:
    image: postgres:16-alpine
    restart: always
    container_name: espera_queue_local_test_db_ci
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=espera_queue_local_test_db_ci
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      # https://stackoverflow.com/a/71315084
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  default:
    external:
      name: cloudbuild

