options:
  logging: CLOUD_LOGGING_ONLY
  logs_bucket: 'gs://espera-queue-be-logs'

steps:
  # Build the container image
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA',
        '.',
      ]
  # Push the container image to Container Registry
  - id: docker-push
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA',
      ]
  # spinning up the test database
  - id: start-test-db
    name: 'docker/compose:1.29.2'
    args:
      [
        '-f',
        'docker-compose.ci.local.yml',
        'up',
        '-d',
        'espera_queue_local_test_db_ci',
      ]
  # Running unit tests
  # needs to allocate enough memory starting with node 18 (NODE_OPTIONS=--max-old-space-size=3000 in test:ci script)
  - id: integration-tests
    name: 'us-west1-docker.pkg.dev/anime-foundation-staging/backend-pr/$COMMIT_SHA'
    args: ['run', 'test:ci']
    env:
      - 'DATABASE_URL=postgresql://postgres:postgres@espera_queue_local_test_db_ci:5432/anime_foundation_test_db?connect_timeout=300'
      - 'NODE_ENV_IS_CI=true'
    waitFor: [docker-build, docker-push, start-test-db]
  # spinning down the test database
  - id: stop-test-db
    name: 'docker/compose:1.29.2'
    args:
      [
        '-f',
        'docker-compose.ci.local.yml',
        'down',
        '-d',
        'espera_queue_local_test_db_ci',
      ]
images:
  - southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA
