options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the container image
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA',
        '.',
      ]
  # Push the container image to Container Registry
  - id: docker-push
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA',
      ]
  # spinning up the test database
  - id: start-test-db
    name: 'docker/compose:1.29.2'
    args:
      [
        '-f',
        'docker-compose.ci.local.yml',
        'up',
        '-d',
        'espera_queue_local_test_db_ci',
      ]
  # Running unit tests
  # needs to allocate enough memory starting with node 18 (NODE_OPTIONS=--max-old-space-size=3000 in test:ci script)
  - id: integration-tests
    name: 'southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA'
    args: ['run', 'test:ci']
    waitFor: [docker-build, docker-push, start-test-db]
  # spinning down the test database
  - id: stop-test-db
    name: 'docker/compose:1.29.2'
    args:
      [
        '-f',
        'docker-compose.ci.local.yml',
        'down',
        '-d',
        'espera_queue_local_test_db_ci',
      ]

# availableSecrets:
#   secretManager:
#     - versionName: projects/965636593689/secrets/JWT_PRIVATE_KEY/versions/latest
#       env: 'JWT_PRIVATE_KEY'
#     - versionName: projects/965636593689/secrets/JWT_PUBLIC_KEY/versions/latest
#       env: 'JWT_PUBLIC_KEY'

images:
  - southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA
