options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the container image
  - id: docker-build
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA',
        '.',
      ]
  # Push the container image to Container Registry
  - id: docker-push
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA',
      ]
  # spinning up the test database
  - id: start-test-db
    name: 'docker/compose:1.29.2'
    args:
      [
        '-f',
        'docker-compose.ci.local.yml',
        'up',
        '-d',
        'espera_queue_local_test_db_ci',
      ]
  # Running unit tests
  # needs to allocate enough memory starting with node 18 (NODE_OPTIONS=--max-old-space-size=3000 in test:ci script)
  - id: integration-tests
    name: 'southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA'
    args: ['run', 'test:ci']
    env:
      - 'DATABASE_URL=postgresql://postgres:postgres@espera_queue_local_test_db_ci:5432/espera_queue_local_test_db_ci?connect_timeout=300'
      - 'NODE_ENV_IS_CI=true'
    waitFor: [docker-build, docker-push, start-test-db]
  # spinning down the test database
  - id: stop-test-db
    name: 'docker/compose:1.29.2'
    args:
      [
        '-f',
        'docker-compose.ci.local.yml',
        'down',
        '-d',
        'espera_queue_local_test_db_ci',
      ]
  # Run database migrations
  # - name: 'southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA'
  #   args: ['run', 'migrate:staging:ci']
  #   secretEnv: ['DATABASE_URL']
  # Deploy container image to Cloud Run, and start api server
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - espera-queue-be-stg
      - --image
      - southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA
      - --args=run,start:prod
      - --region
      - southamerica-east1
      - --port=3000
      - --allow-unauthenticated
      - >-
        --set-secrets=
        DATABASE_URL=DATABASE_URL:latest
      - --set-cloudsql-instances=espera-queue-be:southamerica-east1:espera-queue-staging-db
      # The funny syntax below (^|||^) is to set a different separator. Note: it must be used in the end of the line
      - >-
        --update-env-vars=^|||^
        NODE_ENV=production|||
        PROJECT_ENV=staging

availableSecrets:
  secretManager:
    - versionName: projects/965636593689/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
images:
  - southamerica-east1-docker.pkg.dev/espera-queue-be/espera-queue-be-stg/$COMMIT_SHA
